### ISSUE TITLE
[Question] - nndet_prep Issue - UnboundLocalError: local variable 'block_tensor' referenced before assignment

### ISSUE THREAD

**Issue by QaisarRajput** [MIC-DKFZ/nnDetection#109]
Hi, I am trying to run the basic test of the the repo i am getting an error below. Any idea why this might be happening another user also reported such an issue. - https://github.com/MIC-DKFZ/nnDetection/issues/94
System:
GPU - NVIDIA-AG10
Torch - 1.9.0
CUDA - 10.2
Python - 3.9

Error Log:

```
bash-4.2$ nndet_prep 000 -np 1 -npp 1
/opt/code/nndet/scripts/preprocess.py:381: UserWarning:
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  initialize_config_module(config_module="nndet.conf")
/usr/local/lib/python3.9/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Start dataset info check.
Dataset info check complete.
Start data and label check: test=False
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 8317.08it/s]
Data and label check complete.
Start data and label check: test=True
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 8095.55it/s]
Data and label check complete.
2022-10-14 12:56:18.681 | INFO     | scripts.preprocess:run_cropping_and_convert:75 - Running cropping with overwrite False.
2022-10-14 12:56:18.695 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_0
2022-10-14 12:56:18.696 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_0 already exists and overwrite is deactivated
2022-10-14 12:56:18.696 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_1
2022-10-14 12:56:18.696 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_1 already exists and overwrite is deactivated
2022-10-14 12:56:18.696 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_2
2022-10-14 12:56:18.697 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_2 already exists and overwrite is deactivated
2022-10-14 12:56:18.697 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_3
2022-10-14 12:56:18.697 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_3 already exists and overwrite is deactivated
2022-10-14 12:56:18.697 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_4
2022-10-14 12:56:18.698 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_4 already exists and overwrite is deactivated
2022-10-14 12:56:18.698 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_5
2022-10-14 12:56:18.698 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_5 already exists and overwrite is deactivated
2022-10-14 12:56:18.699 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_6
2022-10-14 12:56:18.699 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_6 already exists and overwrite is deactivated
2022-10-14 12:56:18.699 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_7
2022-10-14 12:56:18.699 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_7 already exists and overwrite is deactivated
2022-10-14 12:56:18.699 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_8
2022-10-14 12:56:18.700 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_8 already exists and overwrite is deactivated
2022-10-14 12:56:18.700 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_9
2022-10-14 12:56:18.700 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_9 already exists and overwrite is deactivated
2022-10-14 12:56:18.715 | INFO     | scripts.preprocess:check_case:264 - Checking /home/dataiku/data/Task000D3_Example/raw_cropped/imagesTr/case_0.npz
2022-10-14 12:56:19.320 | INFO     | scripts.preprocess:check_case:264 - Checking /home/dataiku/data/Task000D3_Example/raw_cropped/imagesTr/case_1.npz
2022-10-14 12:56:19.921 | INFO     | scripts.preprocess:check_case:264 - Checking /home/dataiku/data/Task000D3_Example/raw_cropped/imagesTr/case_2.npz
2022-10-14 12:56:20.521 | INFO     | scripts.preprocess:check_case:264 - Checking /home/dataiku/data/Task000D3_Example/raw_cropped/imagesTr/case_3.npz
2022-10-14 12:56:21.123 | INFO     | scripts.preprocess:check_case:264 - Checking /home/dataiku/data/Task000D3_Example/raw_cropped/imagesTr/case_4.npz
2022-10-14 12:56:21.724 | INFO     | scripts.preprocess:check_case:264 - Checking /home/dataiku/data/Task000D3_Example/raw_cropped/imagesTr/case_5.npz
2022-10-14 12:56:22.324 | INFO     | scripts.preprocess:check_case:264 - Checking /home/dataiku/data/Task000D3_Example/raw_cropped/imagesTr/case_6.npz
2022-10-14 12:56:22.924 | INFO     | scripts.preprocess:check_case:264 - Checking /home/dataiku/data/Task000D3_Example/raw_cropped/imagesTr/case_7.npz
2022-10-14 12:56:23.525 | INFO     | scripts.preprocess:check_case:264 - Checking /home/dataiku/data/Task000D3_Example/raw_cropped/imagesTr/case_8.npz
2022-10-14 12:56:24.127 | INFO     | scripts.preprocess:check_case:264 - Checking /home/dataiku/data/Task000D3_Example/raw_cropped/imagesTr/case_9.npz
2022-10-14 12:56:24.737 | INFO     | scripts.preprocess:run_check:242 - Checked 10 cases in /home/dataiku/data/Task000D3_Example/raw_cropped/imagesTr
2022-10-14 12:56:24.737 | INFO     | scripts.preprocess:run_cropping_and_convert:100 - Crop check successful: Loading check completed
2022-10-14 12:56:24.745 | INFO     | nndet.planning.experiment.base:determine_whether_to_use_mask_for_norm:311 - not using nonzero mask for normalization
2022-10-14 12:56:24.745 | INFO     | nndet.planning.experiment.base:plan_base:164 - Are we using the nonzero maks for normalization? OrderedDict([(0, False)])
2022-10-14 12:56:24.746 | INFO     | nndet.planning.experiment.base:plan_base:166 - Base target spacing is [1. 1. 1.]
2022-10-14 12:56:24.747 | INFO     | nndet.planning.experiment.base:plan_base:169 - Normalization schemes OrderedDict([(0, 'nonCT')])
2022-10-14 12:56:24.747 | WARNING  | nndet.planning.experiment.base:determine_postprocessing:263 - No planning for post-processing implemented.
2022-10-14 12:56:24.748 | INFO     | nndet.planning.experiment.base:plan_base_stage:219 - The median shape of the dataset is [256. 256. 256.]
2022-10-14 12:56:24.748 | INFO     | nndet.planning.experiment.base:plan_base_stage:221 - The max shape in the dataset is [256. 256. 256.]
2022-10-14 12:56:24.749 | INFO     | nndet.planning.experiment.base:plan_base_stage:223 - The min shape in the dataset is [256. 256. 256.]
2022-10-14 12:56:24.749 | INFO     | nndet.planning.experiment.base:plan_base_stage:227 - The transposed median shape of the dataset is [256. 256. 256.]
2022-10-14 12:56:24.750 | INFO     | nndet.planning.architecture.boxes.c002:process_properties:73 - Processing dataset properties
2022-10-14 12:56:27.788 | INFO     | nndet.planning.architecture.boxes.c002:_get_initial_patch_size:340 - Using initial patch size: [256 256 256]
2022-10-14 12:56:27.788 | INFO     | nndet.ptmodule.retinaunet.base:from_config_plan:362 - Architecture overwrites: {} Anchor overwrites: {}
2022-10-14 12:56:27.788 | INFO     | nndet.ptmodule.retinaunet.base:from_config_plan:364 - Building architecture according to plan of not_found
2022-10-14 12:56:27.789 | INFO     | nndet.ptmodule.retinaunet.base:from_config_plan:367 - Start channels: 32; head channels: 128; fpn channels: 128
2022-10-14 12:56:27.789 | INFO     | nndet.core.boxes.anchors:__init__:314 - Discarding anchor generator kwargs {'stride': 1}
2022-10-14 12:56:27.789 | INFO     | nndet.ptmodule.retinaunet.base:_build_encoder:464 - Building:: encoder Encoder: {}
2022-10-14 12:56:27.903 | INFO     | nndet.ptmodule.retinaunet.base:_build_decoder:496 - Building:: decoder UFPNModular: {'min_out_channels': 8, 'upsampling_mode': 'transpose', 'num_lateral': 1, 'norm_lateral': False, 'activation_lateral': False, 'num_out': 1, 'norm_out': False, 'activation_out': False}
2022-10-14 12:56:27.924 | INFO     | nndet.core.boxes.matcher:__init__:253 - Running ATSS Matching with num_candidates=4 and center_in_gt False.
2022-10-14 12:56:27.924 | INFO     | nndet.ptmodule.retinaunet.base:_build_head_classifier:530 - Building:: classifier BCECLassifier: {'num_convs': 1, 'norm_channels_per_group': 16, 'norm_affine': True, 'reduction': 'mean', 'loss_weight': 1.0, 'prior_prob': 0.01}
2022-10-14 12:56:27.931 | INFO     | nndet.arch.heads.classifier:init_weights:215 - Init classifier weights: prior prob 0.01
2022-10-14 12:56:27.937 | INFO     | nndet.ptmodule.retinaunet.base:_build_head_regressor:564 - Building:: regressor GIoURegressor: {'num_convs': 1, 'norm_channels_per_group': 16, 'norm_affine': True, 'reduction': 'sum', 'loss_weight': 1.0, 'learn_scale': True}
2022-10-14 12:56:27.946 | INFO     | nndet.arch.heads.regressor:build_scales:150 - Learning level specific scalar in regressor
2022-10-14 12:56:27.947 | INFO     | nndet.arch.heads.regressor:init_weights:196 - Overwriting regressor conv weight init
2022-10-14 12:56:27.955 | INFO     | nndet.ptmodule.retinaunet.base:_build_head:602 - Building:: head DetectionHeadHNMNative: {} sampler HardNegativeSamplerBatched: {'batch_size_per_image': 32, 'positive_fraction': 0.33, 'pool_size': 20, 'min_neg': 1}
2022-10-14 12:56:27.955 | INFO     | nndet.core.boxes.sampler:__init__:235 - Sampling hard negatives on a per batch basis
2022-10-14 12:56:27.955 | INFO     | nndet.ptmodule.retinaunet.base:_build_segmenter:638 - Building:: segmenter DiCESegmenterFgBg {'dice_kwargs': {'batch_dice': True}}
2022-10-14 12:56:27.956 | INFO     | nndet.losses.segmentation:__init__:108 - Running batch dice True and do bg False in dice loss.
2022-10-14 12:56:27.956 | INFO     | nndet.ptmodule.retinaunet.base:from_config_plan:421 - Model Inference Summary:
detections_per_img: 100
score_thresh: 0
topk_candidates: 10000
remove_small_boxes: 0.01
nms_thresh: 0.6
/usr/local/lib/python3.9/site-packages/torch/cuda/__init__.py:106: UserWarning:
NVIDIA A10G with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA A10G GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
2022-10-14 12:56:28.007 | INFO     | nndet.planning.estimator:estimate:122 - Found available gpu memory: 24788205568 bytes / 23639.875 mb and estimating for 11511726080 bytes / 10978.4375
2022-10-14 12:56:28.049 | INFO     | nndet.planning.estimator:_estimate_mem_available:153 - Estimating in memory.
2022-10-14 12:56:28.049 | INFO     | nndet.planning.estimator:measure:192 - Estimating on cuda:0 with shape [1, 256, 256, 256] and batch size 4 and num_instances 1
2022-10-14 12:56:28.165 | INFO     | nndet.planning.estimator:measure:241 - Caught error (If out of memory error do not worry): CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "/usr/local/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/opt/code/nndet/nndet/utils/check.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/nndet/scripts/preprocess.py", line 406, in main
    run(OmegaConf.to_container(cfg, resolve=True),
  File "/opt/code/nndet/scripts/preprocess.py", line 335, in run
    run_planning_and_process(
  File "/opt/code/nndet/scripts/preprocess.py", line 162, in run_planning_and_process
    plan_identifiers = planner.plan_experiment(
  File "/opt/code/nndet/nndet/planning/experiment/v001.py", line 43, in plan_experiment
    plan_3d = self.plan_base_stage(
  File "/opt/code/nndet/nndet/planning/experiment/base.py", line 234, in plan_base_stage
    architecture_plan = architecture_planner.plan(
  File "/opt/code/nndet/nndet/planning/architecture/boxes/c002.py", line 127, in plan
    res = super().plan(
  File "/opt/code/nndet/nndet/planning/architecture/boxes/base.py", line 346, in plan
    patch_size = self._plan_architecture(
  File "/opt/code/nndet/nndet/planning/architecture/boxes/c002.py", line 205, in _plan_architecture
    _, fits_in_mem = self.estimator.estimate(
  File "/opt/code/nndet/nndet/planning/estimator.py", line 127, in estimate
    res = self._estimate_mem_available(
  File "/opt/code/nndet/nndet/planning/estimator.py", line 154, in _estimate_mem_available
    fixed, dynamic = self.measure(shape=target_shape,
  File "/opt/code/nndet/nndet/planning/estimator.py", line 250, in measure
    del block_tensor
UnboundLocalError: local variable 'block_tensor' referenced before assignment
bash-4.2$





```

**Comment by mibaumgartner** [comment]
Dear @QaisarRajput ,

the original error mentions "Caught error (If out of memory error do not worry): CUDA error: no kernel image is available for execution on the device" which indicates that the GPU where the code is executed on was not present or set via TORCH_CUDA_ARCH_LIST during the building process of nnDetection. Could you double check that?

Best,
Michael

**Comment by QaisarRajput** [comment]
yes, that was correct. I was trying to build the repo on a different GPU/CUDA and was trying to run it on a different environment. Its solved if I build it with exact same configurations.

**Comment by MOMOANNIE** [comment]
> Michael

Hi Michael，I also meet the same problem, but I don't know how to solve it?

![image](https://github.com/MIC-DKFZ/nnDetection/assets/26375536/c69d6661-73e0-48b3-a8ec-8f650aa706d9)

**Comment by MOMOANNIE** [comment]
> Dear @QaisarRajput ,
> 
> the original error mentions "Caught error (If out of memory error do not worry): CUDA error: no kernel image is available for execution on the device" which indicates that the GPU where the code is executed on was not present or set via TORCH_CUDA_ARCH_LIST during the building process of nnDetection. Could you double check that?
> 
> Best, Michael

Hi Michael，I also meet the same problem, but I don't know how to solve it?

![image](https://github.com/MIC-DKFZ/nnDetection/assets/26375536/c69d6661-73e0-48b3-a8ec-8f650aa706d9)
