### ISSUE TITLE
while trying to perform lung nodule detection (task Luna16) using    "detect/engine/scripts/nodule_predict.py"   got the following error   

### ISSUE THREAD

**Issue by DSRajesh** [MIC-DKFZ/nnDetection#110]
[IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 140728168072464)].

I have used  following my docker

1.  nvidia/cuda:11.0-base
2. torch==1.13.0
3. torchvision==0.14.0
The complete error log is below : 

Crop:   0%|                                                        | 0/125 [00:05<?, ?it/s]
Transform:   0%|                                                     | 0/1 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "processor/analyze_all.py", line 516, in <module>
    main()
  File "processor/analyze_all.py", line 418, in main
    full_dict,zsp,vol_arr,rej_list = lung_lobe_multistage_analysis.lung_lobe_multistage_ana lyze(
  File "/pulmonai/./pulmonai/pipelines/lung_lobe_multistage_analysis.py", line 363, in lung _lobe_multistage_analyze
    nodule_predict.predict(task,model, 0 , num_tta_transforms)
  File "/pulmonai/pulmonai/detect/engine/nndet/utils/check.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/pulmonai/./pulmonai/detect/engine/scripts/nodule_predict.py", line 239, in predict
    run(OmegaConf.to_container(cfg, resolve=True),
  File "/pulmonai/./pulmonai/detect/engine/scripts/nodule_predict.py", line 87, in run
    predict_dir(source_dir=source_dir,
  File "/pulmonai/pulmonai/detect/engine/nndet/inference/helper.py", line 104, in predict_d ir
    result = predictor.predict_case({"data": case},
  File "/pulmonai/pulmonai/detect/engine/nndet/inference/predictor.py", line 177, in predic t_case
    self.predict_tiles(tiles)
  File "/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorat e_context
    return func(*args, **kwargs)
  File "/pulmonai/pulmonai/detect/engine/nndet/inference/predictor.py", line 267, in predic t_tiles
    self.predict_with_transformation(
  File "/pulmonai/pulmonai/detect/engine/nndet/inference/predictor.py", line 306, in predic t_with_transformation
    result = model.inference_step(*inp, batch_num=batch_num)
  File "/pulmonai/pulmonai/detect/engine/nndet/ptmodule/base_module.py", line 119, in infer ence_step
    return self.model.inference_step(batch, **kwargs)
  File "/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorat e_context
    return func(*args, **kwargs)
  File "/pulmonai/pulmonai/detect/engine/nndet/core/retina.py", line 399, in inference_step
    prediction = self.postprocess_for_inference(
  File "/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorat e_context
    return func(*args, **kwargs)
  File "/pulmonai/pulmonai/detect/engine/nndet/core/retina.py", line 178, in postprocess_fo r_inference
    boxes, probs, labels = self.postprocess_detections(
  File "/pulmonai/pulmonai/detect/engine/nndet/core/retina.py", line 317, in postprocess_de tections
    boxes, probs, labels = self.postprocess_detections_single_image(boxes, probs, image_sha pe)
  File "/pulmonai/pulmonai/detect/engine/nndet/core/retina.py", line 366, in postprocess_de tections_single_image
    keep = box_utils.batched_nms(boxes, probs, labels, self.nms_thresh)
  File "/pulmonai/pulmonai/detect/engine/nndet/core/boxes/nms.py", line 102, in batched_nms
    return nms(boxes_for_nms, scores, iou_threshold)
  File "/venv/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 14, in decorate _autocast
    return func(*args, **kwargs)
  File "/pulmonai/pulmonai/detect/engine/nndet/core/boxes/nms.py", line 74, in nms
    return nms_fn(boxes.float(), scores.float(), iou_threshold)
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 14072816807 2464)

 It would be great if this is solved

D S Rajesh

**Comment by DSRajesh** [comment]
also       torchmetrics==0.7.0 pytorch-lightning==1.5.9

**Comment by DSRajesh** [comment]
also                       torchmetrics==0.7.0 pytorch-lightning==1. 4. 2

**Comment by DSRajesh** [comment]
also recently i changed the 

torch-1.13.0.dev20220817
torchvision==0.14.0.dev20220817

to

torch-1.13.0.dev20220818
torchvision==0.14.0.dev20220818

and the error log changed like this




![image](https://user-images.githubusercontent.com/60175495/196023475-f6546c0d-7b8d-46db-bd25-d6e5ffc797f7.png)

File "/venv/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/pulmonai/pulmonai/detect/engine/nndet/core/boxes/nms.py", line 74, in nms
    return nms_fn(boxes.float(), scores.float(), iou_threshold)
RuntimeError: Tensors of type TensorImpl do not have strides

**Comment by mibaumgartner** [comment]
Dear @DSRajesh ,

thanks for the detailed Issue. I didn't encounter the first error you reported until now which might indicate some numerical problem. This might be tied to the very recent PyTorch versions (you text says 1.13, while the latest release is 1.12). I encountered the second Issue when upgrading to 1.12 at some point. I just tested the github version with PyTorch 1.12 though and did not encounter any problems. Could try to run the code with PyTorch 1.11? 

Best,
Michael

**Comment by DSRajesh** [comment]
![image](https://user-images.githubusercontent.com/60175495/197358499-4f7cc1b0-924f-4082-9f2d-f1c8a2c87474.png)

Hello [mibaumgartner](https://github.com/mibaumgartner)
I used the following line in my dockerfile:

![image](https://user-images.githubusercontent.com/60175495/197358586-efea1f74-9e73-4602-bce6-16d74203bff0.png)

**Comment by DSRajesh** [comment]
This line was the best (i.e PyTorch 1.11, which you had suggested) I could get from the Pytorch website:

https://pytorch.org/get-started/previous-versions/

**Comment by mibaumgartner** [comment]
Dear @DSRajesh ,

sorry for the delay, the new error indicates that the GPU architecture where you are executing the code on was not set during the installation process. This can be done by setting the environment variable `TORCH_CUDA_ARCH_LIST` in your docker file. 

I updated (and verified) the Dockerfile in the nnDet repo which should work out of the box. If there is not particular reason why you are using a custom Dockerfile I would recommend to use the provided one.

**Comment by mibaumgartner** [comment]
Since there was no update for some time I’ll close this Issue for now.
Please feel free to reopen this Issue if the problem persists or open a new one.
