### ISSUE TITLE
Shared Memory need 24GB - Can this requirement be reduced?

### ISSUE THREAD

**Issue by QaisarRajput** [MIC-DKFZ/nnDetection#113]
Hi,
Thanks for the amazing repo. we are using this on our own dataset, where the infrastructure we have cannot allow for shared memory beyond a certain point (i.e. 12GB). I am getting below error. Is there a way we can reduce this need by reducing multiprocessing parameter or something. For example reducing the concurrent processing. I am not sure the if `env_det_num_threads=6 ` as that control CPU usage and this is related to torch (GPU). Please correct if there is a lack in understanding in my part.

```
 7.7 M     Trainable params
     - 0         Non-trainable params
     - 7.7 M     Total params
     - 30.798    Total estimated model params size (MB)
     - Validation sanity check: 0it [00:00, ?it/s][1mINFO Using validation DataLoader3DOffset with {}[0m
     - [1mINFO Building Sampling Cache for Dataloder[0m
     - Sampling Cache:   0%|          | 0/4 [00:00<?, ?it/s][A
     - Sampling Cache: 100%|██████████| 4/4 [00:00<00:00, 15917.66it/s]
     - [1mINFO Using 5 num_processes and 2 num_cached_per_queue for augmentation.[0m
     - [1mINFO VALIDATION KEYS:
     -  odict_keys(['case_0', 'case_15', 'case_2', 'case_5'])[0m
     - Traceback (most recent call last):
     -   File "/usr/local/lib/python3.9/multiprocessing/queues.py", line 245, in _feed
     -     obj = _ForkingPickler.dumps(obj)
     -   File "/usr/local/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
     -     cls(buf, protocol).dump(obj)
     -   File "/usr/local/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 358, in reduce_storage
     -     fd, size = storage._share_fd_cpu_()
     - RuntimeError: unable to write to file </torch_211_624382216_0>: No space left on device (28)
     - Traceback (most recent call last):
     -   File "/usr/local/lib/python3.9/multiprocessing/queues.py", line 245, in _feed
     -     obj = _ForkingPickler.dumps(obj)
     -   File "/usr/local/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
     -     cls(buf, protocol).dump(obj)
     -   File "/usr/local/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 358, in reduce_storage
     -     fd, size = storage._share_fd_cpu_()
     - RuntimeError: unable to write to file </torch_203_1922446424_4>: No space left on device (28)
     - /home/dataiku/code/nndet/nndet/core/retina.py:358: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
```

**Comment by mibaumgartner** [comment]
Dear @QaisarRajput ,

just to clarify: while the error is thrown by torch, the shared memory does not relate to the available VRAM (of the GPU) but to the RAM (of the CPU). I was able to run the container with 12GB of shared memory as well, maybe there is no space left on your harddrive/ssd? (note: the error does not refer to missing VRAM, that would be an CUDA out of memory error)

Best,
Michael

**Comment by mibaumgartner** [comment]
Since there was no update for some time I’ll close this Issue for now.
Please feel free to reopen this Issue if the problem persists or open a new one.
