### ISSUE TITLE
[Bug] Firstly, the train process is killed, and then I retrained would report TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by Sissi-lu** [MIC-DKFZ/nnDetection#116]
Hi @mibaumgartner, 

I'm very interested in nnDetection. Thank you for your fabulous work. When I tried Task016_Luna, I found some bugs.

### :skull: Bug

After preprocessing and unpacking, I trained the model using the code 'nndet_train 016 --sweep'. And the model started to train. But at epoch 0, and maybe the training process is at about 22%, the terminal displayed 'killed'：

/root/autodl-tmp/nnDetection-main/nndet/utils/check.py:48: UserWarning: Warning: 'det_num_threads' environment variable not set. Please read installation instructions again. Training will not work properly.
  warnings.warn(
'det_verbose' environment variable not set. Continue in verbose mode.
Overwrites: None
/root/autodl-tmp/nnDetection-main/scripts/train.py:179: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  initialize_config_module(config_module="nndet.conf")
/root/miniconda3/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)

using pin_memory on device 0
/root/miniconda3/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:129: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Epoch 0:  29%|█████████████████████▏                                                    | 743/2600[13:33<33:51,  1.09s/it, loss=0.86, v_num=ce20]
Killed

After that, I retrained the model using  'nndet_train 016 --sweep' again, but it was reported as  follows:

Traceback (most recent call last):
  File "/root/miniconda3/bin/nndet_train", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_train')())
  File "/root/autodl-tmp/nnDetection-main/nndet/utils/check.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/root/autodl-tmp/nnDetection-main/scripts/train.py", line 69, in train
    _train(
  File "/root/autodl-tmp/nnDetection-main/scripts/train.py", line 289, in _train
    trainer.fit(module, datamodule=datamodule)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 996, in run_stage
    return self._run_train()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1045, in _run_train
    self.fit_loop.run()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 118, in advance
    _, (batch, is_last) = next(dataloader_iter)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/profiler/base.py", line 104, in profile_iterable
    value = next(iterator)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 625, in prefetch_iterator
    last = next(it)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 546, in __next__
    return self.request_next_batch(self.loader_iters)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 574, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next_fn)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 96, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 561, in next_fn
    batch = next(iterator)
  File "/root/miniconda3/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "/root/miniconda3/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
Exception ignored in: <function tqdm.__del__ at 0x7f8033791280>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1152, in __del__
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1306, in close
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1499, in display
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1155, in __str__
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1457, in format_dict
TypeError: cannot unpack non-iterable NoneType object

I think it was caused probably because I did not unpack again. But I unpacked again, and the same bug still exists. I tried many times to re-preprocessed and re-unpacked, but never solved that problem. The bug is the same.

nnDetection was installed by source.

### Environment
bash:
CPU: 16 cores
RAM: 43 GB
GPU: NVIDIA RTX A5000, 1
storage:
System disk: 5% 1.3G/25G
Data disk: 87% 868G/1000G

nndet_env:
----- PyTorch Information -----
PyTorch Version: 1.10.0+cu113
PyTorch Debug: False
PyTorch CUDA: 11.3
PyTorch Backend cudnn: 8200
PyTorch CUDA Arch List: ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
PyTorch Current Device Capability: (8, 6)
PyTorch CUDA available: True

----- System Information -----
System NVCC: nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0

System Arch List: None
System OMP_NUM_THREADS: 1
System CUDA_HOME is None: True
System CPU Count: 128
Python Version: 3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0]

----- nnDetection Information -----
det_num_threads None
det_data is set True
det_models is set True

thank you very much. I'm looking forward to hearing from you.

Best,
Sissi
11.13

I found that the Warning: 'det_num_threads' environment variable not set. So I set det_num_threads=12, but it didn't work as well.

Epoch 1:  58%|█████████████████████████████████████████▍                              | 1498/2600 [26:35<19:33,  1.06s/it, loss=0.529, v_num=2f8b]WARNING WarmUp was stepped too often, 4000 but only 4000 were expected!
WARNING WarmUp was stepped too often, 4000 but only 4000 were expected!
Epoch 1:  76%|██████████████████████████████████████████████████████▊                 | 1979/2600 [35:19<11:04,  1.07s/it, loss=0.794, v_num=2f8b]
Killed
11.13

I set det_num_threads=6，and it seems that it is working now

**Comment by mibaumgartner** [comment]
Dear @Sissi-lu,

I think your run gets killed because it consume too much memory. Reducing the number of threads, as you as you have already done, should solve your problem. If the problem persists please let me know.

Best,
Michael
