### ISSUE TITLE
No module named 'scripts.generate_example'

### ISSUE THREAD

**Issue by leetesua** [MIC-DKFZ/nnDetection#127]
(envs) usr1@aa-SYS-4029GP-TRT:/data/usr1/nnDetection$ nndet_example

Traceback (most recent call last):
  File "/home/usr1/anaconda3/bin/nndet_example", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_example')())
  File "/home/usr1/anaconda3/bin/nndet_example", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/usr1/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/usr1/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scripts.generate_example'

**Comment by leetesua** [comment]
命令行直接输入nndet_example是什么鬼？
我的ubuntu安装了python3.8和python3.7，我用pip3.8 install -e . 成功安装了nnDetection。但是系统会默认python为python3.7
结果这个东西都不给我指定python的机会，直接在命令行运行nndet_example，好气啊
