### ISSUE TITLE
Dockerfile pytorch version incorrect

### ISSUE THREAD

**Issue by paul-thomson** [MIC-DKFZ/nnDetection#129]
Hi,

I am trying to use nnDetection, building the Dockerfile in the repo. It uses an NVIDIA pre-built image for it's base which is where pytorch comes from. This appears to by pytorch 1.8.0. However, when I use it I get errors because the code appears to depend on pytorch >= 1.10:

Traceback (most recent call last):
  File "/opt/conda/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/opt/code/nndet/nndet/utils/check.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/nndet/scripts/preprocess.py", line 406, in main
    run(OmegaConf.to_container(cfg, resolve=True),
  File "/opt/code/nndet/scripts/preprocess.py", line 335, in run
    run_planning_and_process(
  File "/opt/code/nndet/scripts/preprocess.py", line 162, in run_planning_and_process
    plan_identifiers = planner.plan_experiment(
  File "/opt/code/nndet/nndet/planning/experiment/v001.py", line 43, in plan_experiment
    plan_3d = self.plan_base_stage(
  File "/opt/code/nndet/nndet/planning/experiment/base.py", line 234, in plan_base_stage
    architecture_plan = architecture_planner.plan(
  File "/opt/code/nndet/nndet/planning/architecture/boxes/c002.py", line 127, in plan
    res = super().plan(
  File "/opt/code/nndet/nndet/planning/architecture/boxes/base.py", line 346, in plan
    patch_size = self._plan_architecture(
  File "/opt/code/nndet/nndet/planning/architecture/boxes/c002.py", line 205, in _plan_architecture
    _, fits_in_mem = self.estimator.estimate(
  File "/opt/code/nndet/nndet/planning/estimator.py", line 127, in estimate
    res = self._estimate_mem_available(
  File "/opt/code/nndet/nndet/planning/estimator.py", line 154, in _estimate_mem_available
    fixed, dynamic = self.measure(shape=target_shape,
  File "/opt/code/nndet/nndet/planning/estimator.py", line 229, in measure
    loss_dict, _ = network.train_step(
  File "/opt/code/nndet/nndet/core/retina.py", line 133, in train_step
    pred_detection, anchors, pred_seg = self(images)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/code/nndet/nndet/core/retina.py", line 223, in forward
    anchors = self.anchor_generator(inp, feature_maps_head)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/code/nndet/nndet/core/boxes/anchors.py", line 228, in forward
    anchors_over_all_feature_maps = self.cached_grid_anchors(grid_sizes, strides)
  File "/opt/code/nndet/nndet/core/boxes/anchors.py", line 115, in cached_grid_anchors
    self._cache[key] = self.grid_anchors(grid_sizes, strides)
  File "/opt/code/nndet/nndet/core/boxes/anchors.py", line 364, in grid_anchors
    shift_x, shift_y, shift_z = torch.meshgrid(shifts_x, shifts_y, shifts_z, indexing="ij")
TypeError: meshgrid() got an unexpected keyword argument 'indexing'

The documentation only states that the required pytorch version is 1.7.0+. Could the documentation and/or the Dockerfile be updated so it matches the true dependencies of the code? Thanks

**Comment by yakeworld** [comment]
1. TypeError: meshgrid() got an unexpected keyword argument 'indexing'
File "/opt/code/nndet/nndet/core/boxes/anchors.py", line 364, change to
shift_x, shift_y, shift_z = torch.meshgrid(shifts_x, shifts_y, shifts_z)
2.   File "/opt/code/nndet/nndet/core/retina.py", line 367, in postprocess_detections_single_image
     anchor_idxs = torch.div(idx, self.num_foreground_classes, rounding_mode="floor")
     TypeError: div() got an unexpected keyword argument 'rounding_mode'
    File "/opt/code/nndet/nndet/core/retina.py", line 367,change to
    anchor_idxs = torch.floor_divide(idx, self.num_foreground_classes)

**Comment by mibaumgartner** [comment]
Sorry for the delay, I was on vacation.

The Dockerfile is now updated and uses a newer PyTorch version and the readme now states the dependency of PyTorch >1.10
