### ISSUE TITLE
[Question]Training error -- TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by NickWWWW1** [MIC-DKFZ/nnDetection#131]
Hi all,

I encounter the following message while running "nndet_train". 
 Traceback (most recent call last):
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/bin/nndet_train", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_train')())
  File "/datasets/work/hb-breast-mri-dwt/work/nnDetection/nndet/utils/check.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/datasets/work/hb-breast-mri-dwt/work/nnDetection/scripts/train.py", line 70, in train
    _train(
  File "/datasets/work/hb-breast-mri-dwt/work/nnDetection/scripts/train.py", line 290, in _train
    trainer.fit(module, datamodule=datamodule)
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 996, in run_stage
    return self._run_train()
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1115, in _run_sanity_check
    self._evaluation_loop.run()
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 110, in advance
    output = self.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 154, in evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 211, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 178, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/datasets/work/hb-breast-mri-dwt/work/nnDetection/nndet/ptmodule/retinaunet/base.py", line 172, in validation_step
    losses, prediction = self.model.train_step(
  File "/datasets/work/hb-breast-mri-dwt/work/nnDetection/nndet/core/retina.py", line 146, in train_step
    prediction = self.postprocess_for_inference(
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/datasets/work/hb-breast-mri-dwt/work/nnDetection/nndet/core/retina.py", line 187, in postprocess_for_inference
    boxes, probs, labels = self.postprocess_detections(
  File "/datasets/work/hb-breast-mri-dwt/work/nnDetection/nndet/core/retina.py", line 326, in postprocess_detections
    boxes, probs, labels = self.postprocess_detections_single_image(boxes, probs, image_shape)
  File "/datasets/work/hb-breast-mri-dwt/work/nnDetection/nndet/core/retina.py", line 375, in postprocess_detections_single_image
    keep = box_utils.batched_nms(boxes, probs, labels, self.nms_thresh)
  File "/datasets/work/hb-breast-mri-dwt/work/nnDetection/nndet/core/boxes/nms.py", line 106, in batched_nms
    return nms(boxes_for_nms, scores, iou_threshold)
  File "/datasets/work/hb-breast-mri-dwt/work/env/nnDetection_env/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/datasets/work/hb-breast-mri-dwt/work/nnDetection/nndet/core/boxes/nms.py", line 78, in nms
    return nms_fn(boxes.float(), scores.float(), iou_threshold)
TypeError: 'NoneType' object is not callable
bypassing sigterm
bypassing sigterm

nndet_env information
![image](https://user-images.githubusercontent.com/120084346/208348227-69149be5-cf10-415c-9f95-8752871f7618.png)

I have tried to run this with pytorch 1.13 and pytorch 1.8 with the respective cuda and cudnn version, but without any luck. Any suggestions are greatly appreciated!

**Comment by NickWWWW1** [comment]
The issue is related to NVCC. Now it's fixed

**Comment by wangyueying666** [comment]
I also met the same problem. How did you solve it？

**Comment by karon999** [comment]
I also met the same problem. How did you solve it？
