### ISSUE TITLE
Train several folds at the same time

### ISSUE THREAD

**Issue by vankhoa21991** [MIC-DKFZ/nnDetection#15]
Hello, I faced a new issue when trying to run a second training on the same PC, within a container. As I googled this is related to the master_port environment chosed by torch lightning. Do you know how can I fix this?

INFO Using 1 GPUs for training
INFO Using None plugins for training
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
Using native 16bit precision.
INFO Initialize SWA with swa epoch start 49
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/1
Traceback (most recent call last):
  File "/opt/conda/bin/nndet_train", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_train')())
  File "/opt/nnDetection/nndet/utils/check.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/opt/nnDetection/scripts/train.py", line 69, in train
    _train(
  File "/opt/nnDetection/scripts/train.py", line 284, in _train
    trainer.fit(module, datamodule=datamodule)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 712, in _run
    self.accelerator.setup_environment()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 80, in setup_environment
    self.training_type_plugin.setup_environment()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 112, in setup_environment
    self.setup_distributed()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 198, in setup_distributed
    self.init_ddp_connection()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 272, in init_ddp_connection
    torch_distrib.init_process_group(self.torch_distributed_backend, rank=global_rank, world_size=world_size)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 461, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 179, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)

**Comment by mibaumgartner** [comment]
Hi @vankhoa21991 ,

I didn't encounter that error yet, can you provide a link to the Issue you found? Does the error only occur if you run the training two times within the same container or is it possible to start the container twice and run them independently?

Best,
Michael

**Comment by vankhoa21991** [comment]
I start the container twice and run them independently. The error I found is here https://github.com/PyTorchLightning/pytorch-lightning/issues/2081 . The solution seems like just proposing another port each time training, but we don't have that option yet in the repo.

**Comment by vankhoa21991** [comment]
Update, when I run 2 training without using container it works.

**Comment by mibaumgartner** [comment]
Hi @vankhoa21991 ,

I removed the `ddp` accelerator setting from the config, this should skip the ddp initialization and also the port initialization. Can you check if this (latest master with 29cecb9c0b52745e577076484fd21f88490b390f) fixes your problem?

Best,
Michael

**Comment by vankhoa21991** [comment]
Sorry for the late reply, I solved the issue by adding MASTER_PORT=<random number> nndet_train ...
And each time I choose a different port.
