### ISSUE TITLE
[Question]AttributeError: 'NoneType' object has no attribute 'glob'

### ISSUE THREAD

**Issue by sunqiangzai** [MIC-DKFZ/nnDetection#237]
### :question: Question

the error occurs when I run the following command:
nndet_consolidate 000 RetinaUNetV001_D3V001_3d --sweep_boxes
```
 INFO looking for models in /opt/models/Task000D3_Example/RetinaUNetV001_D3V001_3d
INFO Found training dirs: [PosixPath('/opt/models/Task000D3_Example/RetinaUNetV001_D3V001_3d/fold0'), None, None, None, None]
INFO Consolidate models
Traceback (most recent call last):
  File "/opt/conda/bin/nndet_consolidate", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_consolidate')())
  File "/opt/code/nndet/nndet/utils/check.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/nndet/scripts/consolidate.py", line 159, in main
    consolidate_models(training_dirs, target_dir, ckpt)
  File "/opt/code/nndet/scripts/consolidate.py", line 46, in consolidate_models
    model_paths = list(sd.glob('*.ckpt'))
AttributeError: 'NoneType' object has no attribute 'glob'
```
�

**Comment by mibaumgartner** [comment]
consolidate is only needed when combining the models from different folds, it seems like you only trained fold 0 from the output and thus nnDetectionc an not find the other ones.
