### ISSUE TITLE
[Question] Can some training images have no labels associated with them?

### ISSUE THREAD

**Issue by ArpanGyawali** [MIC-DKFZ/nnDetection#253]
### :question: Question
Hi, i am working on LVO detection task using nn detection. 
I have 3d MIP(Maximum intensity projection) of both positive as well as negative LVO cases. The label is present only for the posiitive LVO. But i need to train on both positive as well as negative cases so that the model learn properly both cases. I need good Sensitivity as well as specificity, but the goal is more sensitivity.
How can i prepare dataset in this case?
Please can someone help me in this case?

**Comment by mibaumgartner** [comment]
Dear @ArpanGyawali ,

this is pretty similar to the question in #252, does my answer there also answer you question? There is nothing special to handle here, just include both positive and negative cases in your dataset and use empty segmentation/json files for the negative cases.

Please note however that nnDetection only supports 3D cases, so operating on the MIP (2D) of a 3D scan might not work.

**Comment by ArpanGyawali** [comment]
Yes, I have created 3d mip for that case. So for the negative case, i need to provide blank segmentation file along with the empty json file right?
Thank you so much

**Comment by mibaumgartner** [comment]
yes, exactly

**Comment by ArpanGyawali** [comment]
Thank you so much

**Comment by ArpanGyawali** [comment]
Hi, @mibaumgartner (regarding images have no labels associated with them)
As you suggested, i created an segmentation file with all 0 for the negative LVO cases (with no object/segmentatiion). 
And in the case of json file for those negative cases, when i created json file with nothing inside it as you suggested. i got this error
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
And when i created json file with just parenthesis {}, i got this error
`KeyError: 'instances'`

The code i ran was
`nndet_prep Task050_LVO --full_check`

**Comment by mibaumgartner** [comment]
Dear @ArpanGyawali ,

sorry, my answer was not quite clear, the json file should contain an empty instances field.

So it should look like

```json
{
   "instances": {}
}
```

**Comment by ArpanGyawali** [comment]
Thanks @mibaumgartner , that solved the above issue. But still again there seems to have problem with blank segmentation file.
I am getting this error.
```
2024-10-24 13:55:23.448 | INFO     | nndet.planning.architecture.boxes.c002:_plan_anchors:258 - Filtered 20 boxes, 0 boxes remaining for anchor planning.
Traceback (most recent call last):
  File "/data/gpfs/projects/punim0401/anaconda3/envs/nndet_venv/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/nnDetection/nndet/utils/check.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/nnDetection/scripts/preprocess.py", line 406, in main
    run(OmegaConf.to_container(cfg, resolve=True),
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/nnDetection/scripts/preprocess.py", line 335, in run
    run_planning_and_process(
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/nnDetection/scripts/preprocess.py", line 162, in run_planning_and_process
    plan_identifiers = planner.plan_experiment(
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/nnDetection/nndet/planning/experiment/v001.py", line 43, in plan_experiment
    plan_3d = self.plan_base_stage(
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/nnDetection/nndet/planning/experiment/base.py", line 234, in plan_base_stage
    architecture_plan = architecture_planner.plan(
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/nnDetection/nndet/planning/architecture/boxes/c002.py", line 127, in plan
    res = super().plan(
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/nnDetection/nndet/planning/architecture/boxes/base.py", line 352, in plan
    anchors = self._plan_anchors(
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/nnDetection/nndet/planning/architecture/boxes/c002.py", line 270, in _plan_anchors
    params = self.find_anchors(boxes_torch, strides.astype(np.int32), anchor_generator)
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/nnDetection/nndet/planning/architecture/boxes/base.py", line 449, in find_anchors
    maxs = sizes.max(dim=0)[0]
IndexError: max(): Expected reduction dim 0 to have non-zero size
```
Is this because there is no box on those images?

**Comment by mibaumgartner** [comment]
```text
2024-10-24 13:55:23.448 | INFO     | nndet.planning.architecture.boxes.c002:_plan_anchors:258 - Filtered 20 boxes, 0 boxes remaining for anchor planning.
```

No, there seems to be something else going on. The above line seems to filter all the boxes which leads to an empty set of boxes. Can you post the rest of the log please?

**Comment by ArpanGyawali** [comment]
Sorry for the bother, I solved the problem. One of the image had non empty annotation while the empty json file.
