### ISSUE TITLE
[Question] Installation issue while pip install -e .    Subprocess-exited-with-error

### ISSUE THREAD

**Issue by ArpanGyawali** [MIC-DKFZ/nnDetection#256]
### :question: Question
My python version:
```Python 3.9.18```

My torch env: 
```
torch==1.13.0+cu117
torchaudio==0.13.0+cu117
torchvision==0.14.0+cu117
```

My nvcc version:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```

Error: pip install -e . -v 
```
pip install -e . -v
Using pip 24.0 from /data/gpfs/projects/punim0401/Arpan/LVO_detection/nndet_env/lib64/python3.9/site-packages/pip (python 3.9)
Obtaining file:///data/gpfs/projects/punim0401/Arpan/LVO_detection/nnDetection
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=40.8.0
    Using cached setuptools-70.0.0-py3-none-any.whl.metadata (5.9 kB)
  Using cached setuptools-70.0.0-py3-none-any.whl (863 kB)
  Installing collected packages: setuptools
  Successfully installed setuptools-70.0.0
  Installing build dependencies ... done
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Getting requirements to build editable
  Traceback (most recent call last):
    File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/nndet_env/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/nndet_env/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/nndet_env/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
      return hook(config_settings)
    File "/tmp/pip-build-env-o9jeu7uu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 448, in get_requires_for_build_editable
      return self.get_requires_for_build_wheel(config_settings)
    File "/tmp/pip-build-env-o9jeu7uu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-o9jeu7uu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-o9jeu7uu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super().run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-o9jeu7uu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 6, in <module>
  ModuleNotFoundError: No module named 'torch'
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /data/gpfs/projects/punim0401/Arpan/LVO_detection/nndet_env/bin/python /data/gpfs/projects/punim0401/Arpan/LVO_detection/nndet_env/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_editable /tmp/tmp3won8tvn
  cwd: /data/gpfs/projects/punim0401/Arpan/LVO_detection/nnDetection
  Getting requirements to build editable ... error
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Why is it saying module not found torch. While i import torch inside the env and it works.
What can be the problem here.

Thanks in advance.

**Comment by mibaumgartner** [comment]
Dear @ArpanGyawali ,

thank you for the detailed Issue, unfortunately I am not able to replicate the error on my machine and thus my guidance is somewhat limited.

I was able to create a nnDetection environment by creating a conda env, install compatible pytorch version via pip and run the installation of nnDetection.

**Comment by ArpanGyawali** [comment]
Thank you so much @mibaumgartner 
I used conda env instead of python venv env, and the previous issue is gone.
But i am getting another issue:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.6.0 requires daal==2021.4.0, which is not installed.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.24.4 which is incompatible.
```

```python -c "import torch; import nndet._C; import nndet"``` This line works without any error, but will it lead to any other errors and issue on the later stage?

**Comment by ArpanGyawali** [comment]
I installed daal==2021.4.0 And the 1st part of issue is gone, now i installed numpy 1.21.1
But again it says:
```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nevergrad 1.0.2 requires numpy>=1.24.0, but you have numpy 1.21.1 which is incompatible```

nevergrad required numpy>=1.24.0 and numba required numpy<1.22,<=1.18


what shouuld i do?

**Comment by mibaumgartner** [comment]
Sorry that the current default versions are not working, we are working on the next release of nnDetection with all efforts right now :) 

Versions which work in my environment:
```
numpy                   1.24.3
nevergrad               0.4.2
torch                   1.13.1
```

**Comment by ArpanGyawali** [comment]
Thank you !
