### ISSUE TITLE
[Question] multiprocessing.pool.RemoteTraceback   Can u help me

### ISSUE THREAD

**Issue by ZHUJJFDU** [MIC-DKFZ/nnDetection#274]
### :question: Question

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/zjc/anaconda3/envs/zjc/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/zjc/anaconda3/envs/zjc/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/zjc/nnDetection/nndet/planning/properties/instance.py", line 162, in analyze_instances_per_case
    instance_class_and_region_sizes(case_id, iseg, props, all_classes)
  File "/home/zjc/nnDetection/nndet/planning/properties/instance.py", line 222, in instance_class_and_region_sizes
    i_cls = instance_classes[instance_id]
KeyError: 67
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zjc/anaconda3/envs/zjc/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/home/zjc/nnDetection/nndet/utils/check.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/zjc/nnDetection/scripts/preprocess.py", line 406, in main
    run(OmegaConf.to_container(cfg, resolve=True),
  File "/home/zjc/nnDetection/scripts/preprocess.py", line 325, in run
    run_dataset_analysis(cropped_output_dir=Path(cfg["host"]["cropped_output_dir"]),
  File "/home/zjc/nnDetection/scripts/preprocess.py", line 129, in run_dataset_analysis
    _ = analyzer.analyze_dataset(properties)
  File "/home/zjc/nnDetection/nndet/planning/analyzer.py", line 80, in analyze_dataset
    props.update(property_fn(self))
  File "/home/zjc/nnDetection/nndet/planning/properties/instance.py", line 46, in analyze_instances
    props_per_case = run_analyze_instances(analyzer, all_classes)
  File "/home/zjc/nnDetection/nndet/planning/properties/instance.py", line 81, in run_analyze_instances
    props = p.starmap(analyze_instances_per_case, zip(
  File "/home/zjc/anaconda3/envs/zjc/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/zjc/anaconda3/envs/zjc/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 67

**Comment by ZHUJJFDU** [comment]
I successfully trained on another homemade dataset and predicted it, and the error was prompted on a different dataset

**Comment by mibaumgartner** [comment]
Dear @ZHUJJFDU ,

the actual error is "KeyError: 67" which indicates that either:

1) Your label are wrong, i.e. there is a json file with instance id 67 but there is no 67 in the mask
2) nnDetection performs a cropping step before analysis, your segmentation was located in a region which is completely 0 and was cropped -> this could for example happen if one of your images is corrupt and suddenly filled with 0's 

Best,
Michael

**Comment by ZHUJJFDU** [comment]
Can you provide the code to convert the mask file of nrrd to nii format I seem to have a problem during the conversion process

**Comment by mibaumgartner** [comment]
You can convert nrrd files to nii via sitk by first loading your image and and saving it in the desired format. If you have problems with mapping instance ids etc. we need more information on your current format and/or examples file(s).
