### ISSUE TITLE
I want to process a large number of lung nodules containing 1mm, 2mm and 3mm, but when I use /project/Luna_016/prepear.py, an error is reported in itk.py: 

### ISSUE THREAD

**Issue by bbqq7788** [MIC-DKFZ/nnDetection#291]
: 2024-12-24 10:20:36.802 | ERROR | __main__:_create_mask:69 - Case 3.3.6.4.1.1.2.156.112605.189250948694021.2023.4.23732 failed with and Traceback (most recent call last): File "prepare.py", line 64, in _create_mask mask = create_circle_mask_itk(data, centers, rads, ndim=3) File "/var/data/W/K/nnDetection-main/nndet/io/itk.py", line 68, in create_circle_mask_itk assert mask_np.max() == _id AssertionError

**Comment by andres2631996** [comment]
Hello, could you check the _centers_ and _rads_ values for that case? Could you see if the case is properly labelled? Perhaps it is just corrupted

**Comment by bbqq7788** [comment]
I modified the code as follows:
def create_circle_mask_itk(image_itk: sitk.Image,
                           world_centers: Sequence[Sequence[float]],
                           world_rads: Sequence[float],
                           ndim: int = 3,
                           ) -> sitk.Image:
    """
    Creates an itk image with circles defined by center points and radii

    Args:
        image_itk: original image (used for the coordinate frame)
        world_centers: Sequence of center points in world coordiantes (x, y, z)
        world_rads: Sequence of radii to use
        ndim: number of spatial dimensions

    Returns:
        sitk.Image: mask with circles
    """
    image_np = sitk.GetArrayFromImage(image_itk)
    min_spacing = min(image_itk.GetSpacing())

    if image_np.ndim > ndim:
        image_np = image_np[0]
    mask_np = np.zeros_like(image_np).astype(np.uint8)

    for _id, (world_center, world_rad) in enumerate(zip(world_centers, world_rads), start=1):
        check_rad = (world_rad / min_spacing) * 1.5  # add some buffer to it
        bounds = []
        center = image_itk.TransformPhysicalPointToContinuousIndex(world_center)[::-1]
        for ax, c in enumerate(center):
            bounds.append((
                max(0, int(c - check_rad - 1)),
                min(mask_np.shape[ax], int(c + check_rad + 1)),
            ))
        coord_box = product(*[list(range(b[0], b[1])) for b in bounds])

        # loop over every pixel position
        marked = False
        for coord in coord_box:
            world_coord = image_itk.TransformIndexToPhysicalPoint(tuple(reversed(coord)))  # reverse order to x, y, z for sitk
            dist = np.linalg.norm(np.array(world_coord) - np.array(world_center))
            if dist <= world_rad:
                mask_np[tuple(coord)] = _id
                marked = True
        if not marked:
            print(f"Warning: No pixels marked for ID {_id}, world_rad: {world_rad}, check_rad: {check_rad},world_center:{world_center}, center:{center},")
        assert mask_np.max() == _id, f"Mask Max Mismatch: Expected {_id}, Got {mask_np.max()}"

    mask_itk = sitk.GetImageFromArray(mask_np)
    mask_itk.SetOrigin(image_itk.GetOrigin())
    mask_itk.SetDirection(image_itk.GetDirection())
    mask_itk.SetSpacing(image_itk.GetSpacing())
    return mask_itk
 
The resulting error statement is as follows:
Warning: No pixels marked for ID 2, world_rad: 1.5, check_rad: 3.5337423312883436,world_center:(64.5999984741211, 37.900001525878906, -330.70001220703125), center:(-85.7974110948602, 315.0239293657976, 369.50521164033745),
2024-12-28 11:13:14.734 | ERROR    | __main__:_create_mask:70 - Case 1.3.6.4.1.1.2.156.112605.189250948694021.2023.4.12852 failed with Mask Max Mismatch: Expected 2, Got 1 and Traceback (most recent call last):
  File "/var/data/W/K/nnDetection-main/projects/Task016_Luna/scripts/prepare.py", line 65, in _create_mask
    mask = create_circle_mask_itk(data, centers, rads, ndim=3)
  File "/var/data/W/K/nnDetection-main/nndet/io/itk.py", line 74, in create_circle_mask_itk
    assert mask_np.max() == _id, f"Mask Max Mismatch: Expected {_id}, Got {mask_np.max()}"
AssertionError: Mask Max Mismatch: Expected 2, Got 1

 world_rad: 1.5, check_rad: 3.5337423312883436,world_center:(64.5999984741211, 37.900001525878906, -330.70001220703125), center:(-85.7974110948602, 315.0239293657976, 369.50521164033745)

When I removed the marking information below 3mm, this problem did not exist.

**Comment by andres2631996** [comment]
Alright, if you have managed to fix the problem, could you make a pull request? We will try to fix this issue

**Comment by bbqq7788** [comment]
No, this problem has not been solved. This problem will not occur if the annotation information below 3mm is removed, but we need to process a large number of images containing lung nodules below 3mm.

**Comment by andres2631996** [comment]
We will try to work on it as soon as possible

**Comment by bbqq7788** [comment]
We are very sorry, we found that our data is abnormal, the code is available. We are very sorry for the trouble caused to you, and thank you very much for your work.
