### ISSUE TITLE
[Bug] TypeError: resample_patient() got an unexpected keyword argument 'cval_data'

### ISSUE THREAD

**Issue by ZheMin-1992** [MIC-DKFZ/nnDetection#30]
Hello,  when I try to use the **nndet_prep** on my data to the pre-processing and planning, it comes an error at the end as follows,

_Traceback (most recent call last):
  File "/home/zmin/.conda/envs/nndetection/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/home/zmin/nnDetection/nndet/utils/check.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/zmin/nnDetection/scripts/preprocess.py", line 475, in main
    run(OmegaConf.to_container(cfg, resolve=True),
  File "/home/zmin/nnDetection/scripts/preprocess.py", line 404, in run
    run_planning_and_process(
  File "/home/zmin/nnDetection/scripts/preprocess.py", line 238, in run_planning_and_process
    planner.run_preprocessing(
  File "/home/zmin/nnDetection/nndet/planning/experiment/base.py", line 348, in run_preprocessing
    preprocessor.run(
  File "/home/zmin/nnDetection/nndet/preprocessing/preprocessor.py", line 195, in run
    p.starmap(self.run_process,
  File "/home/zmin/.conda/envs/nndetection/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/zmin/.conda/envs/nndetection/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: resample_patient() got an unexpected keyword argument 'cval_data'_

Do you have any idea about this? Let me know if more information is needed.

Thanks!
Zhe

**Comment by mibaumgartner** [comment]
Hi @ZheMin-1992 ,

Thanks for the issue! Looks like nnUNet changed its interface for its `resample_patient ` function with its latest release. I'll look into this as soon as I can.

A temporary fix is to downgrade nnunet and batchgenerators:
`
pip install nnunet==1.6.6
pip install batchgenerators==0.21
`

Best,
Michael

**Comment by mibaumgartner** [comment]
I freezed the versions of nnUNet and Batchgenerators (a53f4fc72b3a20c8c32f688eb50522c16bd89d4d) and will bump their versions with new nnDetection releases.

**Comment by ZheMin-1992** [comment]
Thanks, the issue has been solved with your suggestion.
