### ISSUE TITLE
when i use nndet_prep or nndet_example order, error will appear, where did I not configure it?

### ISSUE THREAD

**Issue by hj950815** [MIC-DKFZ/nnDetection#57]
### :question: Question

Traceback (most recent call last):
  File "/home/huangjun/anaconda3/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/home/huangjun/anaconda3/bin/nndet_prep", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/huangjun/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/huangjun/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scripts.preprocess'
(nndetection) huangjun@amax:/data1/huangjun/git_nndetection/nnDetection$ nndet_example
Traceback (most recent call last):
  File "/home/huangjun/anaconda3/bin/nndet_example", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_example')())
  File "/home/huangjun/anaconda3/bin/nndet_example", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/huangjun/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/huangjun/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scripts.generate_example'

**Comment by mibaumgartner** [comment]
Dear @hj950815 ,

I tried reproducing the error but everything worked fine for me. Since the example script is "guarded" by a function which ensures the correct configuration of nnDetection, I think this is not related to the configuration. To me, it sounds like something went wrong during the installation. Can you check that there was no error during the installation? Alternatively, you could try to run the scripts directly via python `python [file].py` instead of using the preconfigured entrypoints (the respective mapping from entrypoint to python file + function can be found in the setup.py). 

Best,
Michael
