### ISSUE TITLE
 raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of " RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full

### ISSUE THREAD

**Issue by hj950815** [MIC-DKFZ/nnDetection#72]
Hello

When I finish executing nndet_prep, there is no error message. I start to execute nndet_train. Usually, this error occurs when I run some epochs. I use A6000. I tried to modify the number of batches, but it seems to have no effect. Can you give me some advice?

Thank you！
  
warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Epoch 0:   1%|▌                                                      | 24/2600 [00:58<1:41:10,  2.36s/it, loss=2.7, v_num=dc82]Exception in background worker 0:
 could not broadcast input array from shape (1,352,114,408) into shape (1,352,114,114)
Epoch 0:   1%|▌                                                      | 25/2600 [01:01<1:40:56,  2.35s/it, loss=2.7, v_num=dc82]Traceback (most recent call last):Traceback (most recent call last):
  File "/home/huangjun/anaconda3/envs/nndetection/bin/nndet_train", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_train')())
  File "/data1/huangjun/git_nndetection/nnDetection/nndet/utils/check.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/data1/huangjun/git_nndetection/nnDetection/scripts/train.py", line 69, in train
    _train(
  File "/data1/huangjun/git_nndetection/nnDetection/scripts/train.py", line 289, in _train
    trainer.fit(module, datamodule=datamodule)
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 996, in run_stage
    return self._run_train()
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1045, in _run_train
    self.fit_loop.run()
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 118, in advance
    _, (batch, is_last) = next(dataloader_iter)
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/profiler/base.py", line 104, in profile_iterable
    value = next(iterator)
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 629, in prefetch_iterator
    for val in it:
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 546, in __next__
    return self.request_next_batch(self.loader_iters)
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 574, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next_fn)
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 96, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 561, in next_fn
    batch = next(iterator)
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "/home/huangjun/anaconda3/envs/nndetection/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
Epoch 0:   1%|          | 25/2600 [01:01<1:41:22,  2.36s/it, loss=2.7, v_num=dc82]

**Comment by mibaumgartner** [comment]
Dear @hj950815 ,

it looks like you are running into a special case during dataloading which I didn't cover / encounter before. Could you add some print statements to the dataloader e.g. at this point https://github.com/MIC-DKFZ/nnDetection/blob/cde847434077a44bbfb516ebf7d0462a2a7fc90f/nndet/io/datamodule/bg_loader.py#L210 to figure out which case if failing and post the shape of that case and the ground truth bounding box coordinates? With that info I could try to reproduce the error. 

Best,
Michael

**Comment by hj950815** [comment]
Do you want me to add print statements like this?

            try:
                if instance_id < 0:
                    candidates = self.load_candidates(case_id=case_id, fg_crop=False)
                    crop = self.get_bg_crop(
                        case_data=case_data,
                        case_seg=case_seg,
                        properties=properties,
                        case_id=case_id,
                        candidates=candidates,
                    )
                else:
                    candidates = self.load_candidates(case_id=case_id, fg_crop=True)
                    crop = self.get_fg_crop(
                        case_data=case_data,
                        case_seg=case_seg,
                        properties=properties,
                        case_id=case_id,
                        instance_id=instance_id,
                        candidates=candidates,
                    )

                data_batch[batch_idx] = save_get_crop(case_data,
                                                    crop=crop,
                                                    mode=self.pad_mode,
                                                    **self.pad_kwargs_data,
                                                    )[0]
                seg_batch[batch_idx] = save_get_crop(case_seg,
                                                    crop=crop,
                                                    mode='constant',
                                                    constant_values=-1,
                                                    )[0]
                case_ids_batch.append(case_id)
                instances_batch.append(properties.pop("instances"))
                properties_batch.append(properties)

            except:
                print('----caseseg----:',case_seg.shape)
                print('----case_data----:',case_data.shape)

And print like this

Epoch 0:   1%|▍                                                     | 21/2600 [00:50<1:37:54,  2.28s/it, loss=2.74, v_num=cc16]
----caseseg----: (1, 332, 80, 294)
----case_data----: (1, 332, 80, 294)
Epoch 0:   1%|▌                                                     | 29/2600 [01:07<1:36:28,  2.25s/it, loss=2.66, v_num=cc16]
Traceback (most recent call last):

**Comment by mibaumgartner** [comment]
I think the problem is specific to a single case in your dataset (probably due to a special case when the foreground object is selected). To get all the relevant info, it would be useful to print some additional infos in addition to your current print statements:

```python
print('----candidates----:', candidates)
print('----instance_id----:', instance_id)
```

**Comment by hj950815** [comment]
You're right, it does seem to be a problem with specific data! Whether the label cannot only take the foreground, or the dataset cannot contain pure negative samples with a label of 0？

----caseseg----: (1, 332, 80, 294)
----case_data----: (1, 332, 80, 294)
----candidates----: {'boxes': array([[162,   6, 204,  48,  42, 126]]), 'instances': [1], 'labels': [0]}
----instance_id----: 1

**Comment by mibaumgartner** [comment]
Dear @hj950815 ,

I found a bug in one of the branches of the conditional statements which is rarely executed, could you locally checkout the `0001_dataloading` branch and try rerunning the training (if you installed nndet with the pip install -e flag no other changes are necessary, otherwise you might need to rerun the pip install command). 

Best,
Michael

**Comment by hj950815** [comment]
Sorry, I didn't understand what you meant, I used pip install -e to install nndet。

**Comment by mibaumgartner** [comment]
Ok, navigate to the nndetection folder and run:
```bash
git pull
git checkout 0001_dataloading
```

And rerun the training.

**Comment by hj950815** [comment]
solved! thank you very much！
