### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by vankhoa21991** [MIC-DKFZ/nnDetection#8]
Hello, I face this issue when running:

nndet_prep 000

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

/home/admvkl@median.cad/.conda/envs/nndet/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py:43: LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics) since v1.3 and will be removed in v1.5
  rank_zero_deprecation(
'det_verbose' environment variable not set. Continue in verbose mode.
/home/admvkl@median.cad/.conda/envs/nndet/lib/python3.8/site-packages/hydra/experimental/initialize.py:68: UserWarning: hydra.experimental.initialize_config_module() is no longer experimental. Use hydra.initialize_config_module().
  warnings.warn(
/home/admvkl@median.cad/.conda/envs/nndet/lib/python3.8/site-packages/hydra/experimental/compose.py:16: UserWarning: hydra.experimental.compose() is no longer experimental. Use hydra.compose()
  warnings.warn(
Start dataset info check.
Dataset info check complete.
Start data and label check.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 13264.72it/s]
Data and label check complete.
Start data and label check.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 14237.28it/s]
Data and label check complete.
2021-06-25 14:50:28.183 | INFO     | scripts.preprocess:run_cropping_and_convert:144 - Running cropping with overwrite False.
2021-06-25 14:50:28.203 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_5
2021-06-25 14:50:28.205 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_5 already exists and overwrite is deactivated
2021-06-25 14:50:28.204 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_1
2021-06-25 14:50:28.204 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_6
2021-06-25 14:50:28.206 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_7
2021-06-25 14:50:28.206 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_6 already exists and overwrite is deactivated
2021-06-25 14:50:28.206 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_7 already exists and overwrite is deactivated
2021-06-25 14:50:28.206 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_1 already exists and overwrite is deactivated
2021-06-25 14:50:28.206 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_8
2021-06-25 14:50:28.207 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_0
2021-06-25 14:50:28.207 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_8 already exists and overwrite is deactivated
2021-06-25 14:50:28.207 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_0 already exists and overwrite is deactivated
2021-06-25 14:50:28.207 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_4
2021-06-25 14:50:28.207 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_9
2021-06-25 14:50:28.208 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_2
2021-06-25 14:50:28.207 | INFO     | nndet.preprocessing.crop:process_data:223 - Processing case case_3
2021-06-25 14:50:28.208 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_4 already exists and overwrite is deactivated
2021-06-25 14:50:28.208 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_9 already exists and overwrite is deactivated
2021-06-25 14:50:28.208 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_2 already exists and overwrite is deactivated
2021-06-25 14:50:28.209 | WARNING  | nndet.preprocessing.crop:process_data:235 - Case case_3 already exists and overwrite is deactivated
2021-06-25 14:50:28.248 | INFO     | scripts.preprocess:check_case:333 - Checking /home/admvkl@median.cad/datasets/MedDec/Task000D3_Example/raw_cropped/imagesTr/case_2.npz
2021-06-25 14:50:28.248 | INFO     | scripts.preprocess:check_case:333 - Checking /home/admvkl@median.cad/datasets/MedDec/Task000D3_Example/raw_cropped/imagesTr/case_0.npz
2021-06-25 14:50:28.248 | INFO     | scripts.preprocess:check_case:333 - Checking /home/admvkl@median.cad/datasets/MedDec/Task000D3_Example/raw_cropped/imagesTr/case_1.npz
2021-06-25 14:50:28.252 | INFO     | scripts.preprocess:check_case:333 - Checking /home/admvkl@median.cad/datasets/MedDec/Task000D3_Example/raw_cropped/imagesTr/case_3.npz
2021-06-25 14:50:28.711 | INFO     | scripts.preprocess:check_case:333 - Checking /home/admvkl@median.cad/datasets/MedDec/Task000D3_Example/raw_cropped/imagesTr/case_4.npz
2021-06-25 14:50:28.724 | INFO     | scripts.preprocess:check_case:333 - Checking /home/admvkl@median.cad/datasets/MedDec/Task000D3_Example/raw_cropped/imagesTr/case_5.npz
2021-06-25 14:50:28.725 | INFO     | scripts.preprocess:check_case:333 - Checking /home/admvkl@median.cad/datasets/MedDec/Task000D3_Example/raw_cropped/imagesTr/case_6.npz
2021-06-25 14:50:28.729 | INFO     | scripts.preprocess:check_case:333 - Checking /home/admvkl@median.cad/datasets/MedDec/Task000D3_Example/raw_cropped/imagesTr/case_7.npz
2021-06-25 14:50:29.168 | INFO     | scripts.preprocess:check_case:333 - Checking /home/admvkl@median.cad/datasets/MedDec/Task000D3_Example/raw_cropped/imagesTr/case_8.npz
2021-06-25 14:50:29.183 | INFO     | scripts.preprocess:check_case:333 - Checking /home/admvkl@median.cad/datasets/MedDec/Task000D3_Example/raw_cropped/imagesTr/case_9.npz
2021-06-25 14:50:29.639 | INFO     | scripts.preprocess:run_check:311 - Checked 10 cases in /home/admvkl@median.cad/datasets/MedDec/Task000D3_Example/raw_cropped/imagesTr
2021-06-25 14:50:29.640 | INFO     | scripts.preprocess:run_cropping_and_convert:169 - Crop check successful: Loading check completed
2021-06-25 14:50:29.702 | INFO     | nndet.planning.properties.instance:analyze_instances_per_case:153 - Processing instance properties of case case_2
2021-06-25 14:50:29.702 | INFO     | nndet.planning.properties.instance:analyze_instances_per_case:153 - Processing instance properties of case case_1
2021-06-25 14:50:29.702 | INFO     | nndet.planning.properties.instance:analyze_instances_per_case:153 - Processing instance properties of case case_0
2021-06-25 14:50:29.706 | INFO     | nndet.planning.properties.instance:analyze_instances_per_case:153 - Processing instance properties of case case_3
2021-06-25 14:50:30.200 | INFO     | nndet.planning.properties.instance:analyze_instances_per_case:153 - Processing instance properties of case case_4
2021-06-25 14:50:30.221 | INFO     | nndet.planning.properties.instance:analyze_instances_per_case:153 - Processing instance properties of case case_5
2021-06-25 14:50:30.223 | INFO     | nndet.planning.properties.instance:analyze_instances_per_case:153 - Processing instance properties of case case_6
2021-06-25 14:50:30.244 | INFO     | nndet.planning.properties.instance:analyze_instances_per_case:153 - Processing instance properties of case case_7
2021-06-25 14:50:30.689 | INFO     | nndet.planning.properties.instance:analyze_instances_per_case:153 - Processing instance properties of case case_8
2021-06-25 14:50:30.708 | INFO     | nndet.planning.properties.instance:analyze_instances_per_case:153 - Processing instance properties of case case_9
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/admvkl@median.cad/.conda/envs/nndet/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/admvkl@median.cad/.conda/envs/nndet/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/admvkl@median.cad/code/public/nnDetection/nndet/planning/properties/instance.py", line 155, in analyze_instances_per_case
    props["num_instances"] = count_instances(props, all_classes)
  File "/home/admvkl@median.cad/code/public/nnDetection/nndet/planning/properties/instance.py", line 176, in count_instances
    instance_classes = list(map(int, props["instances"].values()))
KeyError: 'instances'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/admvkl@median.cad/.conda/envs/nndet/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/home/admvkl@median.cad/code/public/nnDetection/nndet/utils/check.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/admvkl@median.cad/code/public/nnDetection/scripts/preprocess.py", line 475, in main
    run(OmegaConf.to_container(cfg, resolve=True),
  File "/home/admvkl@median.cad/code/public/nnDetection/scripts/preprocess.py", line 394, in run
    run_dataset_analysis(cropped_output_dir=Path(cfg["host"]["cropped_output_dir"]),
  File "/home/admvkl@median.cad/code/public/nnDetection/scripts/preprocess.py", line 198, in run_dataset_analysis
    _ = analyzer.analyze_dataset(properties)
  File "/home/admvkl@median.cad/code/public/nnDetection/nndet/planning/analyzer.py", line 80, in analyze_dataset
    props.update(property_fn(self))
  File "/home/admvkl@median.cad/code/public/nnDetection/nndet/planning/properties/instance.py", line 46, in analyze_instances
    props_per_case = run_analyze_instances(analyzer, all_classes)
  File "/home/admvkl@median.cad/code/public/nnDetection/nndet/planning/properties/instance.py", line 77, in run_analyze_instances
    props = p.starmap(analyze_instances_per_case, zip(
  File "/home/admvkl@median.cad/.conda/envs/nndet/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/admvkl@median.cad/.conda/envs/nndet/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 'instances'

**Comment by vankhoa21991** [comment]
PyTorch Version: <module 'torch.version' from '/home/admvkl@median.cad/.conda/envs/nndet/lib/python3.8/site-packages/torch/version.py'>
PyTorch CUDA: 10.2
PyTorch Backend cudnn: 7605
PyTorch CUDA Arch List: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'compute_37']
PyTorch Current Device Capability: (7, 5)
PyTorch CUDA available: True
System NVCC: nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

System Arch List: None
System OMP_NUM_THREADS: 1
System CUDA_HOME is None: True
Python Version: 3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0]

**Comment by vankhoa21991** [comment]
I found this bug due to a . in my path, so line 85 in load.py will generate error
