### ISSUE TITLE
OmegaConf error

### ISSUE THREAD

**Issue by dalbis** [MIC-DKFZ/nnDetection#88]
Hi,

When I run the following command:
`nndet_consolidate 399 RetinaUNetV001_D3V001_3d --num_folds 1 --sweep_boxes`

I get the following error:
`INFO Consolidating sweep states for refinement.
Traceback (most recent call last):
  File "/opt/conda/bin/nndet_consolidate", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_consolidate')())
  File "/opt/code/nndet/nndet/utils/check.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/nndet/scripts/consolidate.py", line 184, in main
    preprocessed_output_dir = Path(cfg["host"]["preprocessed_output_dir"])
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 377, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/_utils.py", line 873, in format_and_raise
    _raise(ex, cause)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/_utils.py", line 771, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 371, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 453, in _get_impl
    return self._resolve_with_default(
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 98, in _resolve_with_default
    resolved_node = self._maybe_resolve_interpolation(
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/base.py", line 719, in _maybe_resolve_interpolation 
    return self._resolve_interpolation_from_parse_tree(
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/base.py", line 584, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/opt/conda/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue  
    return self.visit(ctx.getChild(0))
  File "/opt/conda/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 301, in visitText
    return self._unescape(list(ctx.getChildren()))
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 389, in _unescape
    text = str(self.visitInterpolation(node))
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/opt/conda/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 921, in accept
    return visitor.visitInterpolationNode(self)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 158, in visitInterpolationNode
    return self.node_interpolation_callback(inter_key, self.memo)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/base.py", line 745, in node_interpolation_callback
    return self._resolve_node_interpolation(inter_key=inter_key, memo=memo)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/base.py", line 664, in _resolve_node_interpolation
    parent, last_key, value = root_node._select_impl(
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/base.py", line 531, in _select_impl
    value = root._maybe_resolve_interpolation(
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/base.py", line 719, in _maybe_resolve_interpolation
    return self._resolve_interpolation_from_parse_tree(
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/base.py", line 584, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/opt/conda/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/opt/conda/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 298, in visitText
    return self.visitInterpolation(c)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/opt/conda/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 1041, in accept
    return visitor.visitInterpolationResolver(self)
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 179, in visitInterpolationResolver
    return self.resolver_interpolation_callback(
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/base.py", line 750, in resolver_interpolation_callback
    return self._evaluate_custom_resolver(
  File "/opt/conda/lib/python3.8/site-packages/omegaconf/base.py", line 702, in _evaluate_custom_resolver
    raise UnsupportedInterpolationType(
omegaconf.errors.UnsupportedInterpolationType: Unsupported interpolation type env
    full_key: host.preprocessed_output_dir
    object_type=dict
`
any idea? I trained only fold0

**Comment by mibaumgartner** [comment]
Dear @dalbis ,

I think you might be on an old commit. The ${env} notation was already updated to ${oc.env} which is supported in newer hydra versions. I tried replicating the problem with hydra 1.1.1 and 1.2.0 without success.

Best,
Michael

**Comment by joeranbosma** [comment]
I made a PR for this change: https://github.com/MIC-DKFZ/nnDetection/pull/91

**Comment by mibaumgartner** [comment]
Good catch @joeranbosma , thanks for submitting a PR!
