### ISSUE TITLE
[Question] - pre-processing step

### ISSUE THREAD

**Issue by aldemirfilho** [MIC-DKFZ/nnDetection#94]
### :question: Question
- hello, could you help me with this error? It was during the pre-processing stage, after 5.5 hours of execution

- if possible, I would also like to know if this error implies the need to redo the pre-processing or if this way it is already possible to extract results. Thank you!

Traceback (most recent call last):
  File "/opt/conda/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/opt/code/nndet/nnDetection/nndet/utils/check.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/nndet/nnDetection/scripts/preprocess.py", line 406, in main
    run(OmegaConf.to_container(cfg, resolve=True),
  File "/opt/code/nndet/nnDetection/scripts/preprocess.py", line 335, in run
    run_planning_and_process(
  File "/opt/code/nndet/nnDetection/scripts/preprocess.py", line 162, in run_planning_and_process
    plan_identifiers = planner.plan_experiment(
  File "/opt/code/nndet/nnDetection/nndet/planning/experiment/v001.py", line 43, in plan_experiment
    plan_3d = self.plan_base_stage(
  File "/opt/code/nndet/nnDetection/nndet/planning/experiment/base.py", line 234, in plan_base_stage
    architecture_plan = architecture_planner.plan(
  File "/opt/code/nndet/nnDetection/nndet/planning/architecture/boxes/c002.py", line 127, in plan
    res = super().plan(
  File "/opt/code/nndet/nnDetection/nndet/planning/architecture/boxes/base.py", line 346, in plan
    patch_size = self._plan_architecture(
  File "/opt/code/nndet/nnDetection/nndet/planning/architecture/boxes/c002.py", line 205, in _plan_architecture
    _, fits_in_mem = self.estimator.estimate(
  File "/opt/code/nndet/nnDetection/nndet/planning/estimator.py", line 127, in estimate
    res = self._estimate_mem_available(
  File "/opt/code/nndet/nnDetection/nndet/planning/estimator.py", line 154, in _estimate_mem_available
    fixed, dynamic = self.measure(shape=target_shape,
  File "/opt/code/nndet/nnDetection/nndet/planning/estimator.py", line 250, in measure
    del block_tensor
UnboundLocalError: local variable 'block_tensor' referenced before assignment

**Comment by mibaumgartner** [comment]
Dear @aldemirfilho ,

the error indicates that a variable is referenced before assignment which would be rather unique since it doesn't occur normally. Could you try to run the nndet example as well?

The results can not be extracted from that point since it is in the middle of the planning stage, the actual preprocessing of the data (resampling and normalization) was not performed yet. 

It is also possible to run individual stages of the preprocessing separately by using the respective overwrites in `https://github.com/MIC-DKFZ/nnDetection/blob/main/nndet/conf/prep/process.yaml` e.g. `nndet_prep ... -o prep=nothing prep.process=True` will only run the planning and processings step which was not run yet. 

Best,
Michael

**Comment by aldemirfilho** [comment]
Thank you!

Aldemir
